# PREDICTING HOUSE PRICE

## DATA UNDERSTANDING

In [1]:
# Import the necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# Load the dataset
df = pd.read_csv("nyumba_sense_data.csv",encoding="latin1")
df

,Title,Property Type,Price,Location,Bedrooms,Bathrooms,Size,Amenities,Surroundings,Created At,URL,Record Type
0,3 Bed Townhouse with En Suite at Dagoretti Road,Townhouse,"KSh 22,500,000","Gikambura, Kikuyu",3 Bedrooms,3 Bathrooms,223 sqm,"Alarm, Backup Generator, En Suite, Fibre Inter...","Bus Stop, Hospital, Scenic View, School, Shopp...",21-Jan-26,https://www.buyrentkenya.com/listings/3-bedroo...,Original
1,4 Bed House in Kiambu Road,House,"KSh 78,000,000",Kiambu Road,4 Bedrooms,NaN,NaN,NaN,NaN,5-Dec-25,https://www.buyrentkenya.com/listings/4-bedroo...,Original
2,6 Bed Townhouse with En Suite in Lavington,Townhouse,"KSh 160,000,000",Lavington,6 Bedrooms,7 Bathrooms,450 sqm,"Alarm, Backup Generator, En Suite, Fibre Inter...","Bus Stop, Shopping Centre, Golf Course, Hospit...",6-Feb-26,https://www.buyrentkenya.com/listings/6-bedroo...,Original
3,4 Bed House with En Suite at Apple Cross,House,"KSh 130,000,000",Lavington,4 Bedrooms,5 Bathrooms,NaN,"Alarm, Backup Generator, Fibre Internet, En Su...","Bus Stop, Shopping Centre, Hospital, Scenic Vi...",18-Feb-26,https://www.buyrentkenya.com/listings/4-bedroo...,Original
4,2 Bed Villa with En Suite at Tembo Court,Villa,"KSh 21,000,000",Malindi,2 Bedrooms,3 Bathrooms,506 sqm,"Aircon, Alarm, Backup Generator, En Suite, Fib...","Bus Stop, Golf Course, Hospital, Scenic View, ...",17-Feb-26,https://www.buyrentkenya.com/listings/furnishe...,Original
...,...,...,...,...,...,...,...,...,...,...,...,...
8995,4 Bed House with En Suite in Syokimau,House,"KSh 33,343,535",Syokimau,4 Bedrooms,3 Bathrooms,NaN,"Alarm, Backup Generator, En Suite, Fibre Inter...","Bus Stop, Shopping Centre, Hospital, School",NaN,NaN,Synthetic
8996,4 Bed House with En Suite in Kiambu Road,House,"KSh 29,612,584",Kiambu Road,4 Bedrooms,6 Bathrooms,496 sqm,"En Suite, Fibre Internet, Walk In Closet, Back...","Bus Stop, Golf Course, Hospital, Scenic View, ...",NaN,NaN,Synthetic
8997,4 Bed Villa with En Suite at Off Loresho Ridge,Villa,"KSh 98,753,738","Loresho, Westlands",4 Bedrooms,5 Bathrooms,770 sqm,"Service Charge Included, Alarm, Backup Generat...","School, Scenic View, Hospital, Golf Course, Bu...",NaN,NaN,Synthetic
8998,4 Bed Townhouse with En Suite at Kimalat -Enka...,Townhouse,"KSh 14,719,230",Kitengela,4 Bedrooms,4 Bathrooms,168 sqm,"Alarm, Backup Generator, En Suite, Serviced, B...","Bus Stop, Hospital, School, Shopping Centre",NaN,NaN,Synthetic
8999,4 Bed Townhouse with En Suite in Lavington,Townhouse,"KSh 60,494,038",Lavington,4 Bedrooms,4 Bathrooms,255 sqm,"Aircon, Alarm, Backup Generator, En Suite, Fib...","Bus Stop, Golf Course, Hospital, Scenic View, ...",NaN,NaN,Synthetic

In [4]:
# Get the shape of the data
print(f"The dataset has {df.shape[1]} variables/columns with {df.shape[0]} observations/rows")

The dataset has 12 variables/columns with 9000 observations/rows

In [5]:
# The information about the variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          9000 non-null   object
 1   Property Type  9000 non-null   object
 2   Price          9000 non-null   object
 3   Location       9000 non-null   object
 4   Bedrooms       9000 non-null   object
 5   Bathrooms      8627 non-null   object
 6   Size           5965 non-null   object
 7   Amenities      8713 non-null   object
 8   Surroundings   8096 non-null   object
 9   Created At     800 non-null    object
 10  URL            800 non-null    object
 11  Record Type    9000 non-null   object
dtypes: object(12)
memory usage: 843.9+ KB

In [6]:
# Attain the statistical summary of numeric variables
df.describe().T

,count,unique,top,freq
Title,9000,434,5 Bed Townhouse with En Suite in Lavington,911
Property Type,9000,3,House,3764
Price,9000,8370,"KSh 85,000,000",37
Location,9000,77,Lavington,2400
Bedrooms,9000,11,5 Bedrooms,3324
Bathrooms,8627,11,5 Bathrooms,2389
Size,5965,1382,20 sqm,1041
Amenities,8713,633,"Alarm, Backup Generator, En Suite, Fibre Inter...",472
Surroundings,8096,125,"Bus Stop, Golf Course, Hospital, Scenic View, ...",2028
Created At,800,85,17-Feb-26,94
URL,800,800,https://www.buyrentkenya.com/listings/3-bedroo...,1
Record Type,9000,2,Synthetic,8200

In [15]:
# Check for duplicates
df.duplicated().sum()

6

In [17]:
# Drop the duplicates
df = df.drop_duplicates()

# re-check for duplicates
df.duplicated().sum()

0